### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by Bsvrd** [AllanBB/SoundBoardApp#5]
We must create a splash screen. The link is not currently working but found a video on youtube by the same group. https://www.youtube.com/watch?v=muz6QLIgrC0 I think it would be sufficient to put the logo on the splash screen and nothing else.

**Comment by pgodin** [comment]
https://www.genuinecoder.com/javafx-splash-screen-loading-screen/ the website Scott provided us is working today

**Comment by pgodin** [comment]
I just asked Scott, and the requirement is simply to "have a splash screen" it doesn't need to functionality behind it. Just showing the logo for 3-5 sec before getting to the main view would be fine.
